plugins = []
headers = []

[functions]

[functions."*"]

[build]
publish = "C:\\Users\\ahmad\\OBSTeam"
publishOrigin = "default"

[build.environment]

[build.processing]

[build.processing.css]

[build.processing.html]

[build.processing.images]

[build.processing.js]

[build.services]

[[redirects]]
from = "http://*"
to = "https://www.obsteamdivlb.com/:splat"
status = 301.0
force = true

[redirects.query]

[redirects.conditions]

[redirects.headers]

[[redirects]]
from = "https://obsteamdivlb.com/*"
to = "https://www.obsteamdivlb.com/:splat"
status = 301.0
force = true

[redirects.query]

[redirects.conditions]

[redirects.headers]